<?php

use Illuminate\Database\Seeder;

class DaysTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('days')->insert([

            // September
            ['number' => 3,  'name_id' => 1, 'week_id' => 1, 'month_id' => 1, 'active' => true],
            ['number' => 4,  'name_id' => 2, 'week_id' => 1, 'month_id' => 1, 'active' => true],
            ['number' => 5,  'name_id' => 3, 'week_id' => 1, 'month_id' => 1, 'active' => true],
            ['number' => 6,  'name_id' => 4, 'week_id' => 1, 'month_id' => 1, 'active' => true],
            ['number' => 7,  'name_id' => 5, 'week_id' => 1, 'month_id' => 1, 'active' => true],
            ['number' => 8,  'name_id' => 6, 'week_id' => 1, 'month_id' => 1, 'active' => false],
            ['number' => 9,  'name_id' => 7, 'week_id' => 1, 'month_id' => 1, 'active' => false],
            ['number' => 10, 'name_id' => 1, 'week_id' => 2, 'month_id' => 1, 'active' => true],
            ['number' => 11, 'name_id' => 2, 'week_id' => 2, 'month_id' => 1, 'active' => true],
            ['number' => 12, 'name_id' => 3, 'week_id' => 2, 'month_id' => 1, 'active' => true],
            ['number' => 13, 'name_id' => 4, 'week_id' => 2, 'month_id' => 1, 'active' => true],
            ['number' => 14, 'name_id' => 5, 'week_id' => 2, 'month_id' => 1, 'active' => true],
            ['number' => 15, 'name_id' => 6, 'week_id' => 2, 'month_id' => 1, 'active' => false],
            ['number' => 16, 'name_id' => 7, 'week_id' => 2, 'month_id' => 1, 'active' => false],
            ['number' => 17, 'name_id' => 1, 'week_id' => 3, 'month_id' => 1, 'active' => true],
            ['number' => 18, 'name_id' => 2, 'week_id' => 3, 'month_id' => 1, 'active' => true],
            ['number' => 19, 'name_id' => 3, 'week_id' => 3, 'month_id' => 1, 'active' => true],
            ['number' => 20, 'name_id' => 4, 'week_id' => 3, 'month_id' => 1, 'active' => true],
            ['number' => 21, 'name_id' => 5, 'week_id' => 3, 'month_id' => 1, 'active' => true],
            ['number' => 22, 'name_id' => 6, 'week_id' => 3, 'month_id' => 1, 'active' => false],
            ['number' => 23, 'name_id' => 7, 'week_id' => 3, 'month_id' => 1, 'active' => false],
            ['number' => 24, 'name_id' => 1, 'week_id' => 4, 'month_id' => 1, 'active' => true],
            ['number' => 25, 'name_id' => 2, 'week_id' => 4, 'month_id' => 1, 'active' => true],
            ['number' => 26, 'name_id' => 3, 'week_id' => 4, 'month_id' => 1, 'active' => true],
            ['number' => 27, 'name_id' => 4, 'week_id' => 4, 'month_id' => 1, 'active' => true],
            ['number' => 28, 'name_id' => 5, 'week_id' => 4, 'month_id' => 1, 'active' => true],
            ['number' => 29, 'name_id' => 6, 'week_id' => 4, 'month_id' => 1, 'active' => false],
            ['number' => 30, 'name_id' => 7, 'week_id' => 4, 'month_id' => 1, 'active' => false],

            // October
            ['number' => 1,  'name_id' => 1, 'week_id' => 5, 'month_id' => 2, 'active' => true],
            ['number' => 2,  'name_id' => 2, 'week_id' => 5, 'month_id' => 2, 'active' => true],
            ['number' => 3,  'name_id' => 3, 'week_id' => 5, 'month_id' => 2, 'active' => true],
            ['number' => 4,  'name_id' => 4, 'week_id' => 5, 'month_id' => 2, 'active' => true],
            ['number' => 5,  'name_id' => 5, 'week_id' => 5, 'month_id' => 2, 'active' => true],
            ['number' => 6,  'name_id' => 6, 'week_id' => 5, 'month_id' => 2, 'active' => false],
            ['number' => 7,  'name_id' => 7, 'week_id' => 5, 'month_id' => 2, 'active' => false],
            ['number' => 8,  'name_id' => 1, 'week_id' => 6, 'month_id' => 2, 'active' => true],
            ['number' => 9,  'name_id' => 2, 'week_id' => 6, 'month_id' => 2, 'active' => true],
            ['number' => 10, 'name_id' => 3, 'week_id' => 6, 'month_id' => 2, 'active' => true],
            ['number' => 11, 'name_id' => 4, 'week_id' => 6, 'month_id' => 2, 'active' => true],
            ['number' => 12, 'name_id' => 5, 'week_id' => 6, 'month_id' => 2, 'active' => true],
            ['number' => 13, 'name_id' => 6, 'week_id' => 6, 'month_id' => 2, 'active' => false],
            ['number' => 14, 'name_id' => 7, 'week_id' => 6, 'month_id' => 2, 'active' => false],
            ['number' => 15, 'name_id' => 1, 'week_id' => 7, 'month_id' => 2, 'active' => true],
            ['number' => 16, 'name_id' => 2, 'week_id' => 7, 'month_id' => 2, 'active' => true],
            ['number' => 17, 'name_id' => 3, 'week_id' => 7, 'month_id' => 2, 'active' => true],
            ['number' => 18, 'name_id' => 4, 'week_id' => 7, 'month_id' => 2, 'active' => true],
            ['number' => 19, 'name_id' => 5, 'week_id' => 7, 'month_id' => 2, 'active' => true],
            ['number' => 20, 'name_id' => 6, 'week_id' => 7, 'month_id' => 2, 'active' => false],
            ['number' => 21, 'name_id' => 7, 'week_id' => 7, 'month_id' => 2, 'active' => false],
            ['number' => 22, 'name_id' => 1, 'week_id' => 8, 'month_id' => 2, 'active' => true],
            ['number' => 23, 'name_id' => 2, 'week_id' => 8, 'month_id' => 2, 'active' => true],
            ['number' => 24, 'name_id' => 3, 'week_id' => 8, 'month_id' => 2, 'active' => true],
            ['number' => 25, 'name_id' => 4, 'week_id' => 8, 'month_id' => 2, 'active' => true],
            ['number' => 26, 'name_id' => 5, 'week_id' => 8, 'month_id' => 2, 'active' => true],
            ['number' => 27, 'name_id' => 6, 'week_id' => 8, 'month_id' => 2, 'active' => false],
            ['number' => 28, 'name_id' => 7, 'week_id' => 8, 'month_id' => 2, 'active' => false],
            ['number' => 29, 'name_id' => 1, 'week_id' => 9, 'month_id' => 2, 'active' => true],
            ['number' => 30, 'name_id' => 2, 'week_id' => 9, 'month_id' => 2, 'active' => true],
            ['number' => 31, 'name_id' => 3, 'week_id' => 9, 'month_id' => 2, 'active' => true],

            // November
            ['number' => 1,  'name_id' => 4, 'week_id' => 9, 'month_id' => 3, 'active' => true],
            ['number' => 2,  'name_id' => 5, 'week_id' => 9, 'month_id' => 3, 'active' => true],
            ['number' => 3,  'name_id' => 6, 'week_id' => 9, 'month_id' => 3, 'active' => false],
            ['number' => 4,  'name_id' => 7, 'week_id' => 9, 'month_id' => 3, 'active' => false],
            ['number' => 5,  'name_id' => 1, 'week_id' => 10, 'month_id' => 3, 'active' => true],
            ['number' => 6,  'name_id' => 2, 'week_id' => 10, 'month_id' => 3, 'active' => true],
            ['number' => 7,  'name_id' => 3, 'week_id' => 10, 'month_id' => 3, 'active' => true],
            ['number' => 8,  'name_id' => 4, 'week_id' => 10, 'month_id' => 3, 'active' => true],
            ['number' => 9,  'name_id' => 5, 'week_id' => 10, 'month_id' => 3, 'active' => true],
            ['number' => 10, 'name_id' => 6, 'week_id' => 10, 'month_id' => 3, 'active' => false],
            ['number' => 11, 'name_id' => 7, 'week_id' => 10, 'month_id' => 3, 'active' => false],
            ['number' => 12, 'name_id' => 1, 'week_id' => 11, 'month_id' => 3, 'active' => true],
            ['number' => 13, 'name_id' => 2, 'week_id' => 11, 'month_id' => 3, 'active' => true],
            ['number' => 14, 'name_id' => 3, 'week_id' => 11, 'month_id' => 3, 'active' => true],
            ['number' => 15, 'name_id' => 4, 'week_id' => 11, 'month_id' => 3, 'active' => true],
            ['number' => 16, 'name_id' => 5, 'week_id' => 11, 'month_id' => 3, 'active' => true],
            ['number' => 17, 'name_id' => 6, 'week_id' => 11, 'month_id' => 3, 'active' => false],
            ['number' => 18, 'name_id' => 7, 'week_id' => 11, 'month_id' => 3, 'active' => false],
            ['number' => 19, 'name_id' => 1, 'week_id' => 12, 'month_id' => 3, 'active' => true],
            ['number' => 20, 'name_id' => 2, 'week_id' => 12, 'month_id' => 3, 'active' => true],
            ['number' => 21, 'name_id' => 3, 'week_id' => 12, 'month_id' => 3, 'active' => true],
            ['number' => 22, 'name_id' => 4, 'week_id' => 12, 'month_id' => 3, 'active' => true],
            ['number' => 23, 'name_id' => 5, 'week_id' => 12, 'month_id' => 3, 'active' => true],
            ['number' => 24, 'name_id' => 6, 'week_id' => 12, 'month_id' => 3, 'active' => false],
            ['number' => 25, 'name_id' => 7, 'week_id' => 12, 'month_id' => 3, 'active' => false],
            ['number' => 26, 'name_id' => 1, 'week_id' => 13, 'month_id' => 3, 'active' => true],
            ['number' => 27, 'name_id' => 2, 'week_id' => 13, 'month_id' => 3, 'active' => true],
            ['number' => 28, 'name_id' => 3, 'week_id' => 13, 'month_id' => 3, 'active' => true],
            ['number' => 29, 'name_id' => 4, 'week_id' => 13, 'month_id' => 3, 'active' => true],
            ['number' => 30, 'name_id' => 5, 'week_id' => 13, 'month_id' => 3, 'active' => true],

            // December
            ['number' => 1,  'name_id' => 6, 'week_id' => 13, 'month_id' => 4, 'active' => false],
            ['number' => 2,  'name_id' => 7, 'week_id' => 13, 'month_id' => 4, 'active' => false],
            ['number' => 3,  'name_id' => 1, 'week_id' => 14, 'month_id' => 4, 'active' => true],
            ['number' => 4,  'name_id' => 2, 'week_id' => 14, 'month_id' => 4, 'active' => true],
            ['number' => 5,  'name_id' => 3, 'week_id' => 14, 'month_id' => 4, 'active' => true],
            ['number' => 6,  'name_id' => 4, 'week_id' => 14, 'month_id' => 4, 'active' => true],
            ['number' => 7,  'name_id' => 5, 'week_id' => 14, 'month_id' => 4, 'active' => true],
            ['number' => 8,  'name_id' => 6, 'week_id' => 14, 'month_id' => 4, 'active' => false],
            ['number' => 9,  'name_id' => 7, 'week_id' => 14, 'month_id' => 4, 'active' => false],
            ['number' => 10, 'name_id' => 1, 'week_id' => 15, 'month_id' => 4, 'active' => true],
            ['number' => 11, 'name_id' => 2, 'week_id' => 15, 'month_id' => 4, 'active' => true],
            ['number' => 12, 'name_id' => 3, 'week_id' => 15, 'month_id' => 4, 'active' => true],
            ['number' => 13, 'name_id' => 4, 'week_id' => 15, 'month_id' => 4, 'active' => true],
            ['number' => 14, 'name_id' => 5, 'week_id' => 15, 'month_id' => 4, 'active' => true],
            ['number' => 15, 'name_id' => 6, 'week_id' => 15, 'month_id' => 4, 'active' => false],
            ['number' => 16, 'name_id' => 7, 'week_id' => 15, 'month_id' => 4, 'active' => false],
            ['number' => 17, 'name_id' => 1, 'week_id' => 16, 'month_id' => 4, 'active' => true],
            ['number' => 18, 'name_id' => 2, 'week_id' => 16, 'month_id' => 4, 'active' => true],
            ['number' => 19, 'name_id' => 3, 'week_id' => 16, 'month_id' => 4, 'active' => true],
            ['number' => 20, 'name_id' => 4, 'week_id' => 16, 'month_id' => 4, 'active' => true],
            ['number' => 21, 'name_id' => 5, 'week_id' => 16, 'month_id' => 4, 'active' => true],
            ['number' => 22, 'name_id' => 6, 'week_id' => 16, 'month_id' => 4, 'active' => false],
            ['number' => 23, 'name_id' => 7, 'week_id' => 16, 'month_id' => 4, 'active' => false],
            ['number' => 24, 'name_id' => 1, 'week_id' => 17, 'month_id' => 4, 'active' => true],
            ['number' => 25, 'name_id' => 2, 'week_id' => 17, 'month_id' => 4, 'active' => true],
            ['number' => 26, 'name_id' => 3, 'week_id' => 17, 'month_id' => 4, 'active' => true],
            ['number' => 27, 'name_id' => 4, 'week_id' => 17, 'month_id' => 4, 'active' => true],
            ['number' => 28, 'name_id' => 5, 'week_id' => 17, 'month_id' => 4, 'active' => true],
            ['number' => 29, 'name_id' => 6, 'week_id' => 17, 'month_id' => 4, 'active' => false],
            ['number' => 30, 'name_id' => 7, 'week_id' => 17, 'month_id' => 4, 'active' => false],
            ['number' => 31, 'name_id' => 1, 'week_id' => 18, 'month_id' => 4, 'active' => true],

            // January
            ['number' => 1,  'name_id' => 2, 'week_id' => 18, 'month_id' => 5, 'active' => true],
            ['number' => 2,  'name_id' => 3, 'week_id' => 18, 'month_id' => 5, 'active' => true],
            ['number' => 3,  'name_id' => 4, 'week_id' => 18, 'month_id' => 5, 'active' => true],
            ['number' => 4,  'name_id' => 5, 'week_id' => 18, 'month_id' => 5, 'active' => true],
            ['number' => 5,  'name_id' => 6, 'week_id' => 18, 'month_id' => 5, 'active' => false],
            ['number' => 6,  'name_id' => 7, 'week_id' => 18, 'month_id' => 5, 'active' => false],
            ['number' => 7,  'name_id' => 1, 'week_id' => 19, 'month_id' => 5, 'active' => true],
            ['number' => 8,  'name_id' => 2, 'week_id' => 19, 'month_id' => 5, 'active' => true],
            ['number' => 9,  'name_id' => 3, 'week_id' => 19, 'month_id' => 5, 'active' => true],
            ['number' => 10, 'name_id' => 4, 'week_id' => 19, 'month_id' => 5, 'active' => true],
            ['number' => 11, 'name_id' => 5, 'week_id' => 19, 'month_id' => 5, 'active' => true],
            ['number' => 12, 'name_id' => 6, 'week_id' => 19, 'month_id' => 5, 'active' => false],
            ['number' => 13, 'name_id' => 7, 'week_id' => 19, 'month_id' => 5, 'active' => false],
            ['number' => 14, 'name_id' => 1, 'week_id' => 20, 'month_id' => 5, 'active' => true],
            ['number' => 15, 'name_id' => 2, 'week_id' => 20, 'month_id' => 5, 'active' => true],
            ['number' => 16, 'name_id' => 3, 'week_id' => 20, 'month_id' => 5, 'active' => true],
            ['number' => 17, 'name_id' => 4, 'week_id' => 20, 'month_id' => 5, 'active' => true],
            ['number' => 18, 'name_id' => 5, 'week_id' => 20, 'month_id' => 5, 'active' => true],
            ['number' => 19, 'name_id' => 6, 'week_id' => 20, 'month_id' => 5, 'active' => false],
            ['number' => 20, 'name_id' => 7, 'week_id' => 20, 'month_id' => 5, 'active' => false],
            ['number' => 21, 'name_id' => 1, 'week_id' => 21, 'month_id' => 5, 'active' => true],
            ['number' => 22, 'name_id' => 2, 'week_id' => 21, 'month_id' => 5, 'active' => true],
            ['number' => 23, 'name_id' => 3, 'week_id' => 21, 'month_id' => 5, 'active' => true],
            ['number' => 24, 'name_id' => 4, 'week_id' => 21, 'month_id' => 5, 'active' => true],
            ['number' => 25, 'name_id' => 5, 'week_id' => 21, 'month_id' => 5, 'active' => true],
            ['number' => 26, 'name_id' => 6, 'week_id' => 21, 'month_id' => 5, 'active' => false],
            ['number' => 27, 'name_id' => 7, 'week_id' => 21, 'month_id' => 5, 'active' => false],
            ['number' => 28, 'name_id' => 1, 'week_id' => 22, 'month_id' => 5, 'active' => true],
            ['number' => 29, 'name_id' => 2, 'week_id' => 22, 'month_id' => 5, 'active' => true],
            ['number' => 30, 'name_id' => 3, 'week_id' => 22, 'month_id' => 5, 'active' => true],
            ['number' => 31, 'name_id' => 4, 'week_id' => 22, 'month_id' => 5, 'active' => true],

            // February
            ['number' => 1,  'name_id' => 5, 'week_id' => 22, 'month_id' => 6, 'active' => true],
            ['number' => 2,  'name_id' => 6, 'week_id' => 22, 'month_id' => 6, 'active' => false],
            ['number' => 3,  'name_id' => 7, 'week_id' => 22, 'month_id' => 6, 'active' => false],
            ['number' => 4,  'name_id' => 1, 'week_id' => 23, 'month_id' => 6, 'active' => true],
            ['number' => 5,  'name_id' => 2, 'week_id' => 23, 'month_id' => 6, 'active' => true],
            ['number' => 6,  'name_id' => 3, 'week_id' => 23, 'month_id' => 6, 'active' => true],
            ['number' => 7,  'name_id' => 4, 'week_id' => 23, 'month_id' => 6, 'active' => true],
            ['number' => 8,  'name_id' => 5, 'week_id' => 23, 'month_id' => 6, 'active' => true],
            ['number' => 9,  'name_id' => 6, 'week_id' => 23, 'month_id' => 6, 'active' => false],
            ['number' => 10, 'name_id' => 7, 'week_id' => 23, 'month_id' => 6, 'active' => false],
            ['number' => 11, 'name_id' => 1, 'week_id' => 24, 'month_id' => 6, 'active' => true],
            ['number' => 12, 'name_id' => 2, 'week_id' => 24, 'month_id' => 6, 'active' => true],
            ['number' => 13, 'name_id' => 3, 'week_id' => 24, 'month_id' => 6, 'active' => true],
            ['number' => 14, 'name_id' => 4, 'week_id' => 24, 'month_id' => 6, 'active' => true],
            ['number' => 15, 'name_id' => 5, 'week_id' => 24, 'month_id' => 6, 'active' => true],
            ['number' => 16, 'name_id' => 6, 'week_id' => 24, 'month_id' => 6, 'active' => false],
            ['number' => 17, 'name_id' => 7, 'week_id' => 24, 'month_id' => 6, 'active' => false],
            ['number' => 18, 'name_id' => 1, 'week_id' => 25, 'month_id' => 6, 'active' => true],
            ['number' => 19, 'name_id' => 2, 'week_id' => 25, 'month_id' => 6, 'active' => true],
            ['number' => 20, 'name_id' => 3, 'week_id' => 25, 'month_id' => 6, 'active' => true],
            ['number' => 21, 'name_id' => 4, 'week_id' => 25, 'month_id' => 6, 'active' => true],
            ['number' => 22, 'name_id' => 5, 'week_id' => 25, 'month_id' => 6, 'active' => true],
            ['number' => 23, 'name_id' => 6, 'week_id' => 25, 'month_id' => 6, 'active' => false],
            ['number' => 24, 'name_id' => 7, 'week_id' => 25, 'month_id' => 6, 'active' => false],
            ['number' => 25, 'name_id' => 1, 'week_id' => 26, 'month_id' => 6, 'active' => true],
            ['number' => 26, 'name_id' => 2, 'week_id' => 26, 'month_id' => 6, 'active' => true],
            ['number' => 27, 'name_id' => 3, 'week_id' => 26, 'month_id' => 6, 'active' => true],
            ['number' => 28, 'name_id' => 4, 'week_id' => 26, 'month_id' => 6, 'active' => true],

            // March
            ['number' => 1,  'name_id' => 5, 'week_id' => 26, 'month_id' => 7, 'active' => true],
            ['number' => 2,  'name_id' => 6, 'week_id' => 26, 'month_id' => 7, 'active' => false],
            ['number' => 3,  'name_id' => 7, 'week_id' => 26, 'month_id' => 7, 'active' => false],
            ['number' => 4,  'name_id' => 1, 'week_id' => 27, 'month_id' => 7, 'active' => true],
            ['number' => 5,  'name_id' => 2, 'week_id' => 27, 'month_id' => 7, 'active' => true],
            ['number' => 6,  'name_id' => 3, 'week_id' => 27, 'month_id' => 7, 'active' => true],
            ['number' => 7,  'name_id' => 4, 'week_id' => 27, 'month_id' => 7, 'active' => true],
            ['number' => 8,  'name_id' => 5, 'week_id' => 27, 'month_id' => 7, 'active' => true],
            ['number' => 9,  'name_id' => 6, 'week_id' => 27, 'month_id' => 7, 'active' => false],
            ['number' => 10, 'name_id' => 7, 'week_id' => 27, 'month_id' => 7, 'active' => false],
            ['number' => 11, 'name_id' => 1, 'week_id' => 28, 'month_id' => 7, 'active' => true],
            ['number' => 12, 'name_id' => 2, 'week_id' => 28, 'month_id' => 7, 'active' => true],
            ['number' => 13, 'name_id' => 3, 'week_id' => 28, 'month_id' => 7, 'active' => true],
            ['number' => 14, 'name_id' => 4, 'week_id' => 28, 'month_id' => 7, 'active' => true],
            ['number' => 15, 'name_id' => 5, 'week_id' => 28, 'month_id' => 7, 'active' => true],
            ['number' => 16, 'name_id' => 6, 'week_id' => 28, 'month_id' => 7, 'active' => false],
            ['number' => 17, 'name_id' => 7, 'week_id' => 28, 'month_id' => 7, 'active' => false],
            ['number' => 18, 'name_id' => 1, 'week_id' => 29, 'month_id' => 7, 'active' => true],
            ['number' => 19, 'name_id' => 2, 'week_id' => 29, 'month_id' => 7, 'active' => true],
            ['number' => 20, 'name_id' => 3, 'week_id' => 29, 'month_id' => 7, 'active' => true],
            ['number' => 21, 'name_id' => 4, 'week_id' => 29, 'month_id' => 7, 'active' => true],
            ['number' => 22, 'name_id' => 5, 'week_id' => 29, 'month_id' => 7, 'active' => true],
            ['number' => 23, 'name_id' => 6, 'week_id' => 29, 'month_id' => 7, 'active' => false],
            ['number' => 24, 'name_id' => 7, 'week_id' => 29, 'month_id' => 7, 'active' => false],
            ['number' => 25, 'name_id' => 1, 'week_id' => 30, 'month_id' => 7, 'active' => true],
            ['number' => 26, 'name_id' => 2, 'week_id' => 30, 'month_id' => 7, 'active' => true],
            ['number' => 27, 'name_id' => 3, 'week_id' => 30, 'month_id' => 7, 'active' => true],
            ['number' => 28, 'name_id' => 4, 'week_id' => 30, 'month_id' => 7, 'active' => true],
            ['number' => 29, 'name_id' => 5, 'week_id' => 30, 'month_id' => 7, 'active' => true],
            ['number' => 30, 'name_id' => 6, 'week_id' => 30, 'month_id' => 7, 'active' => false],
            ['number' => 31, 'name_id' => 7, 'week_id' => 30, 'month_id' => 7, 'active' => false],

            // April
            ['number' => 1,  'name_id' => 1, 'week_id' => 31, 'month_id' => 8, 'active' => true],
            ['number' => 2,  'name_id' => 2, 'week_id' => 31, 'month_id' => 8, 'active' => true],
            ['number' => 3,  'name_id' => 3, 'week_id' => 31, 'month_id' => 8, 'active' => true],
            ['number' => 4,  'name_id' => 4, 'week_id' => 31, 'month_id' => 8, 'active' => true],
            ['number' => 5,  'name_id' => 5, 'week_id' => 31, 'month_id' => 8, 'active' => true],
            ['number' => 6,  'name_id' => 6, 'week_id' => 31, 'month_id' => 8, 'active' => false],
            ['number' => 7,  'name_id' => 7, 'week_id' => 31, 'month_id' => 8, 'active' => false],
            ['number' => 8,  'name_id' => 1, 'week_id' => 32, 'month_id' => 8, 'active' => true],
            ['number' => 9,  'name_id' => 2, 'week_id' => 32, 'month_id' => 8, 'active' => true],
            ['number' => 10, 'name_id' => 3, 'week_id' => 32, 'month_id' => 8, 'active' => true],
            ['number' => 11, 'name_id' => 4, 'week_id' => 32, 'month_id' => 8, 'active' => true],
            ['number' => 12, 'name_id' => 5, 'week_id' => 32, 'month_id' => 8, 'active' => true],
            ['number' => 13, 'name_id' => 6, 'week_id' => 32, 'month_id' => 8, 'active' => false],
            ['number' => 14, 'name_id' => 7, 'week_id' => 32, 'month_id' => 8, 'active' => false],
            ['number' => 15, 'name_id' => 1, 'week_id' => 33, 'month_id' => 8, 'active' => true],
            ['number' => 16, 'name_id' => 2, 'week_id' => 33, 'month_id' => 8, 'active' => true],
            ['number' => 17, 'name_id' => 3, 'week_id' => 33, 'month_id' => 8, 'active' => true],
            ['number' => 18, 'name_id' => 4, 'week_id' => 33, 'month_id' => 8, 'active' => true],
            ['number' => 19, 'name_id' => 5, 'week_id' => 33, 'month_id' => 8, 'active' => true],
            ['number' => 20, 'name_id' => 6, 'week_id' => 33, 'month_id' => 8, 'active' => false],
            ['number' => 21, 'name_id' => 7, 'week_id' => 33, 'month_id' => 8, 'active' => false],
            ['number' => 22, 'name_id' => 1, 'week_id' => 34, 'month_id' => 8, 'active' => true],
            ['number' => 23, 'name_id' => 2, 'week_id' => 34, 'month_id' => 8, 'active' => true],
            ['number' => 24, 'name_id' => 3, 'week_id' => 34, 'month_id' => 8, 'active' => true],
            ['number' => 25, 'name_id' => 4, 'week_id' => 34, 'month_id' => 8, 'active' => true],
            ['number' => 26, 'name_id' => 5, 'week_id' => 34, 'month_id' => 8, 'active' => true],
            ['number' => 27, 'name_id' => 6, 'week_id' => 34, 'month_id' => 8, 'active' => false],
            ['number' => 28, 'name_id' => 7, 'week_id' => 34, 'month_id' => 8, 'active' => false],
            ['number' => 29, 'name_id' => 1, 'week_id' => 35, 'month_id' => 8, 'active' => true],
            ['number' => 30, 'name_id' => 2, 'week_id' => 35, 'month_id' => 8, 'active' => true],

            // May
            ['number' => 1,  'name_id' => 3, 'week_id' => 35, 'month_id' => 9, 'active' => true],
            ['number' => 2,  'name_id' => 4, 'week_id' => 35, 'month_id' => 9, 'active' => true],
            ['number' => 3,  'name_id' => 5, 'week_id' => 35, 'month_id' => 9, 'active' => true],
            ['number' => 4,  'name_id' => 6, 'week_id' => 35, 'month_id' => 9, 'active' => false],
            ['number' => 5,  'name_id' => 7, 'week_id' => 35, 'month_id' => 9, 'active' => false],
            ['number' => 6,  'name_id' => 1, 'week_id' => 36, 'month_id' => 9, 'active' => true],
            ['number' => 7,  'name_id' => 2, 'week_id' => 36, 'month_id' => 9, 'active' => true],
            ['number' => 8,  'name_id' => 3, 'week_id' => 36, 'month_id' => 9, 'active' => true],
            ['number' => 9,  'name_id' => 4, 'week_id' => 36, 'month_id' => 9, 'active' => true],
            ['number' => 10, 'name_id' => 5, 'week_id' => 36, 'month_id' => 9, 'active' => true],
            ['number' => 11, 'name_id' => 6, 'week_id' => 36, 'month_id' => 9, 'active' => false],
            ['number' => 12, 'name_id' => 7, 'week_id' => 36, 'month_id' => 9, 'active' => false],
            ['number' => 13, 'name_id' => 1, 'week_id' => 37, 'month_id' => 9, 'active' => true],
            ['number' => 14, 'name_id' => 2, 'week_id' => 37, 'month_id' => 9, 'active' => true],
            ['number' => 15, 'name_id' => 3, 'week_id' => 37, 'month_id' => 9, 'active' => true],
            ['number' => 16, 'name_id' => 4, 'week_id' => 37, 'month_id' => 9, 'active' => true],
            ['number' => 17, 'name_id' => 5, 'week_id' => 37, 'month_id' => 9, 'active' => true],
            ['number' => 18, 'name_id' => 6, 'week_id' => 37, 'month_id' => 9, 'active' => false],
            ['number' => 19, 'name_id' => 7, 'week_id' => 37, 'month_id' => 9, 'active' => false],
            ['number' => 20, 'name_id' => 1, 'week_id' => 38, 'month_id' => 9, 'active' => true],
            ['number' => 21, 'name_id' => 2, 'week_id' => 38, 'month_id' => 9, 'active' => true],
            ['number' => 22, 'name_id' => 3, 'week_id' => 38, 'month_id' => 9, 'active' => true],
            ['number' => 23, 'name_id' => 4, 'week_id' => 38, 'month_id' => 9, 'active' => true],
            ['number' => 24, 'name_id' => 5, 'week_id' => 38, 'month_id' => 9, 'active' => true],
            ['number' => 25, 'name_id' => 6, 'week_id' => 38, 'month_id' => 9, 'active' => false],
            ['number' => 26, 'name_id' => 7, 'week_id' => 38, 'month_id' => 9, 'active' => false],
            ['number' => 27, 'name_id' => 1, 'week_id' => 39, 'month_id' => 9, 'active' => true],
            ['number' => 28, 'name_id' => 2, 'week_id' => 39, 'month_id' => 9, 'active' => true],
            ['number' => 29, 'name_id' => 3, 'week_id' => 39, 'month_id' => 9, 'active' => true],
            ['number' => 30, 'name_id' => 4, 'week_id' => 39, 'month_id' => 9, 'active' => true],
            ['number' => 31, 'name_id' => 5, 'week_id' => 39, 'month_id' => 9, 'active' => true],
        ]);
    }
}
